import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Parent Stories - Capture Your Parents' Life Stories",
    template: "%s | Parent Stories",
  },
  description: "Know their story before the chapter closes. Capture your parents' life stories through meaningful questions before it's too late.",
  keywords: ["parent stories", "family history", "life stories", "interview questions", "family memories", "genealogy", "family legacy"],
  authors: [{ name: "Parent Stories" }],
  creator: "Parent Stories",
  publisher: "Parent Stories",
  metadataBase: new URL("https://parent-stories.vercel.app"),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://parent-stories.vercel.app",
    siteName: "Parent Stories",
    title: "Parent Stories - Capture Your Parents' Life Stories",
    description: "Know their story before the chapter closes. Capture your parents' life stories through meaningful questions before it's too late.",
    // Images are automatically generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Parent Stories - Capture Your Parents' Life Stories",
    description: "Know their story before the chapter closes. Capture your parents' life stories through meaningful questions before it's too late.",
    // Images are automatically generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    // Add Google Search Console verification if needed
    // google: "verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
